### ISSUE TITLE
update field names & config panel

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/nodebb-plugin-fusionauth-oidc#1]
1. Update field names to match the table description in the README
2. Can add additional text to this panel, a description or something? If so, let's discuss. 
3. Default `Email claim` field to `email`
4. Can we format the code with a smaller indent? or is this the NodeBB style guideline? (HTML and JS have a 8 space indent or something like that)

**Comment by tyduptyler13** [comment]
1. Done
2. We can add whatever to the page. There aren't any built in tooltips (that i found) so we will have to craft our own if thats the direction you want to go.
3. It was originally designed to be defaulted but it didn't seem to work... I'll keep trying things.
4. The formatting was inherited from the original repo, we can change it to whatever.

**Comment by robotdan** [comment]
> We can add whatever to the page. There aren't any built in tooltips (that i found) so we will have to craft our own if thats the direction you want to go.

Maybe a heading with a description of the plugin, and a link to the GitHub with the configuration walk through? 

If you want to mock it up you can do a screen share or an ngrok and I can take a look. 

> Default Email claim field to email

If you can't get it - not a big deal. If we can't get it defaulted, then we could change the field to 'Override email claim' or something like that and leave it empty - and then assume `email` unless provided.
