### ISSUE TITLE
Adding Plugin to New Install

### ISSUE THREAD

**Issue by allebone** [FusionAuth/nodebb-plugin-fusionauth-oidc#11]
Howdy! I am completing an initial setup, and after setting things up to the point of incorporating Outside Identity, I install the FusionAuth Plugin....and now my server won't start.  I've narrowed it down to FusionAuth-oidc by Disabling all the plugins, one-by-one, and removing them (with a rebuild and restart after each). 

Running Newest NodeBB 1.17.

Its not a FusionAuth Config issue, as I am not able to make it that far. 

Is there a place I can grab some logs, or error messages to further assist?

Thank You,

Bryan

**Comment by mooreds** [comment]
This looks like a duplicate of #12 . Mind if I close?

**Comment by allebone** [comment]
Sure
